# Let's try to maintain dockerfile here.
# Last updated: 11/11/2022

FROM mambaorg/micromamba:1.0.0-jammy
LABEL maintainer "Hyunwoo Cho <hc27oclock@gmail.com>"

# bash shell
SHELL ["/bin/bash", "-c"]

USER root
RUN apt-get install -y unattended-upgrades

CMD ["/bin/bash"]

