# Let's try to maintain dockerfile here.
# Last updated: 11/10/2022

FROM us.gcr.io/broad-dsp-gcr-public/terra-jupyter-gatk:2.2.8
LABEL maintainer "Hyunwoo Cho <hc27oclock@gmail.com>"

# RUN 'R -e '

