# Let's try to maintain dockerfile here.
# Last updated: 11/10/2022

FROM us.gcr.io/broad-dsp-gcr-public/terra-jupyter-r:2.1.6
LABEL maintainer "Hyunwoo Cho <hc27oclock@gmail.com>"

CMD ["/bin/bash"]
